language: go

cache:
  directories:
    - $GOPATH/pkg/mod

jobs:
  fast_finish: true
  include:
    - go: 1.12.x
    - go: 1.13.x
    - go: 1.14.x
    - go: 1.x
    - go: tip
# Adding ppc64le jobs
    - go: 1.12.x
      arch: ppc64le
    - go: 1.13.x
      arch: ppc64le
    - go: 1.14.x
      arch: ppc64le
    - go: 1.x
      arch: ppc64le
    - go: tip
      arch: ppc64le
  allow_failures:
    - go: tip

before_install:
  - export GO111MODULE=off
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/lint/golint
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - GO111MODULE=on

install:
  - go mod tidy
  - git diff --exit-code go.mod
  - git diff --exit-code go.sum
  - go mod download

script:
  # Test Code quality
  - go vet ./...
  - ${GOPATH}/bin/golint ./...
  - go test -covermode=count -coverprofile=profile.cov ./...

  # Test buildable on most common platforms, beyond Linux
  - if [[ "$TRAVIS_CPU_ARCH" != "ppc64le" ]]; then  GOOS=darwin go build ./... ;  GOOS=windows go build ./... ; fi

  # Best effort: notify coveralls. It's too unstable, ignore errors.
  - if [[ "$TRAVIS_CPU_ARCH" != "ppc64le" ]]; then $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci || exit 0 ; fi
